# Generated by Django 5.1.7 on 2025-03-17 01:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Boufarik', 'Boufarik'), ('Mouzaia', 'Mouzaia'), ('Larbaa', 'Larbaa'), ('OuladYaich', 'Oulad Yaich'), ('ElWouroud', 'El Wouroud'), ('Bougara', 'Bougara'), ('Afroun', 'Afroun')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('ResponsableDeBoufarik', 'Responsable de Boufarik'), ('ResponsableDeMouzaia', 'Responsable de Mouzaia'), ('ResponsableDeLarbaa', 'Responsable de Larbaa'), ('ResponsableDeOuladYaich', 'Responsable de Oulad Yaich'), ('ResponsableDeElWouroud', 'Responsable de El Wouroud'), ('ResponsableDeBougara', 'Responsable de Bougara'), ('ResponsableDeAfroun', 'Responsable de Afroun')], max_length=30)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(default='Unknown', max_length=255)),
                ('surname', models.CharField(default='Unknown', max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('client_type', models.CharField(choices=[('Corporate', 'Corporate'), ('Residential', 'Residential')], max_length=20)),
                ('address', models.TextField(default='Unknown', max_length=255)),
                ('observation', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('etat', models.CharField(choices=[('Non Traité', 'Non Traité'), ('Décédé', 'Décédé'), ('Avocat', 'Avocat'), ('Huissier', 'Huissier'), ('Juridique', 'Juridique'), ('En Cours', 'En Cours'), ('Payment Réglé', 'Payment Réglé')], default='Non Traité', max_length=20)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='pfe.region')),
            ],
        ),
        migrations.CreateModel(
            name='DateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_etat', models.CharField(choices=[('Non Traité', 'Non Traité'), ('Décédé', 'Décédé'), ('Avocat', 'Avocat'), ('Huissier', 'Huissier'), ('Juridique', 'Juridique'), ('En Cours', 'En Cours'), ('Payment Réglé', 'Payment Réglé')], default='Non Traité', max_length=20)),
                ('new_etat', models.CharField(choices=[('Non Traité', 'Non Traité'), ('Décédé', 'Décédé'), ('Avocat', 'Avocat'), ('Huissier', 'Huissier'), ('Juridique', 'Juridique'), ('En Cours', 'En Cours'), ('Payment Réglé', 'Payment Réglé')], default='Non Traité', max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='date_changes', to='pfe.client')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facture_id', models.CharField(max_length=50, unique=True)),
                ('amount', models.FloatField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='pfe.client')),
            ],
        ),
    ]
