# Generated by Django 5.1.7 on 2025-03-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='region',
            field=models.CharField(choices=[('Boufarik', 'Boufarik'), ('Mouzaia', 'Mouzaia'), ('Larbaa', 'Larbaa'), ('OuladYaich', 'Oulad Yaich'), ('ElWouroud', 'El Wouroud'), ('Bougara', 'Bougara'), ('Afroun', 'Afroun')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
