# Generated by Django 5.1.7 on 2025-03-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Responsable de Boufarik'), (3, 'Responsable de Mouzaia'), (4, 'Responsable de Larbaa'), (5, 'Responsable de Oulad Yaich'), (6, 'Responsable de El Wouroud'), (7, 'Responsable de Bougara'), (8, 'Responsable de Afroun')], default='1'),
        ),
    ]
