# Generated by Django 5.2 on 2025-04-26 17:22

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0008_datechange_changed_by_alter_client_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datechange',
            name='changed_by',
        ),
        migrations.AlterField(
            model_name='client',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistoricalClient',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(default='Unknown', max_length=255)),
                ('surname', models.CharField(default='Unknown', max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('client_type', models.CharField(choices=[('Corporate', 'Corporate'), ('Residential', 'Residential')], max_length=20)),
                ('region', models.CharField(choices=[('Boufarik', 'Boufarik'), ('Mouzaia', 'Mouzaia'), ('Larbaa', 'Larbaa'), ('OuladYaich', 'Oulad Yaich'), ('ElWouroud', 'El Wouroud'), ('Bougara', 'Bougara'), ('Afroun', 'Afroun')], max_length=50)),
                ('address', models.TextField(default='Unknown', max_length=255)),
                ('observation', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('etat', models.CharField(choices=[('Non Traité', 'Non Traité'), ('Décédé', 'Décédé'), ('Avocat', 'Avocat'), ('Huissier', 'Huissier'), ('Juridique', 'Juridique'), ('En Cours', 'En Cours'), ('Payment Réglé', 'Payment Réglé')], default='Non Traité', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical client',
                'verbose_name_plural': 'historical clients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
