# Generated by Django 5.2 on 2025-05-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0009_remove_datechange_changed_by_alter_client_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='etat',
            field=models.CharField(choices=[('Non Traité', 'Non Traité'), ('Décédé', 'Décédé'), ('Avocat', 'Avocat'), ('Huissier', 'Huissier'), ('Juridique', 'Juridique'), ('Paiement en cours', 'Paiement en cours'), ('Payment Réglé', 'Payment Réglé')], default='Non Traité', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='datechange',
            name='new_etat',
            field=models.CharField(choices=[('Non Traité', 'Non Traité'), ('Décédé', 'Décédé'), ('Avocat', 'Avocat'), ('Huissier', 'Huissier'), ('Juridique', 'Juridique'), ('Paiement en cours', 'Paiement en cours'), ('Payment Réglé', 'Payment Réglé')], default='Non Traité', max_length=20),
        ),
        migrations.AlterField(
            model_name='datechange',
            name='previous_etat',
            field=models.CharField(choices=[('Non Traité', 'Non Traité'), ('Décédé', 'Décédé'), ('Avocat', 'Avocat'), ('Huissier', 'Huissier'), ('Juridique', 'Juridique'), ('Paiement en cours', 'Paiement en cours'), ('Payment Réglé', 'Payment Réglé')], default='Non Traité', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='etat',
            field=models.CharField(choices=[('Non Traité', 'Non Traité'), ('Décédé', 'Décédé'), ('Avocat', 'Avocat'), ('Huissier', 'Huissier'), ('Juridique', 'Juridique'), ('Paiement en cours', 'Paiement en cours'), ('Payment Réglé', 'Payment Réglé')], default='Non Traité', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
