# Generated by Django 5.2 on 2025-05-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0010_alter_client_etat_alter_client_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='personal_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='personal_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
